### ISSUE TITLE
OrganizationService.get_orgs() might exceed recursion limit

### ISSUE THREAD

**Issue by rerb** [AASHE/python-membersuite-api-client#14]
If we ever get TransportErrors for a while -- continuously for a few minutes maybe -- OrganizationService.get_orgs() is going to exceed the recursion limit.

Need to worry about it?  Don't know.  Not usually, at least, since TransportErrors are rare (are they?).  To the user it might just look like a stalled site until the recursion limit is exceeded, then a 500.  Would be good detective work to trace that back to get_orgs().

https://github.com/AASHE/python-membersuite-api-client/blob/memberships/membersuite_api_client/organizations/services.py#L58

**Comment by baronvonvaderham** [comment]
It's fine, the recursion limit only matters for the tests. I wanted to be able to test that the recursion happens correctly and it concatenates properly, but not have to wait through it querying hundreds of things. @jamstooks had the idea to manually determine the pagination and set a variable to cap the number of loops.

For your normal use of that function, it will default to 200 records. Max-recursion for python is on the order of thousands of calls, so unless we let this thing keep trying and failing for a few weeks, we should be ok.

**Comment by rerb** [comment]
Not talking about recursion limit in get_orgs(), just the recursion that happens each time a TransportError happens.  If MS's network interface goes down for 15 minutes, for example, and each time get_orgs() queries MS it gets a TransportError, the recursion limit doesn't come into play, does it?  We get a tight loop of query/exception/repeat going.

**Comment by baronvonvaderham** [comment]
Ah, sorry I misunderstood.

That's definitely a possibility, but I think it's still ok. Even if it goes down for a significant time (10+ minutes), it takes 60 seconds for the request to time out per iteration before that exception is kicked. It will be recurring a few extra times, for sure, but not an enormous number that will cause problems.

If it does go down for hours or something, then the python interpreter itself will kick an error that it detected an infinite loop and exited. That would show up in our logs, and/or get detected by Sentry, and we'd know the sync failed.

Additionally, maybe we can specify a default limit instead of None? Something big, like 200 or something, that should never be reached in normal operation, and create a custom exception message to be returned if that's reached?

**Comment by jamstooks** [comment]
I like the idea of a custom exception for this situation. Maybe there's yet another parameter for the method called `max_timeouts` that defaults to 10 or something? Then that custom exception could be thrown and we would see it in the logs...

**Comment by rerb** [comment]
Did not know this.

On Feb 10, 2017, 10:37 AM -0500, Scott Johnson <notifications@github.com>, wrote:

> the python interpreter itself will kick an error that it detected an infinite loop and exited.

-- 
Join us in San Antonio, TX from Oct. 15 - 18 for the 2017 AASHE Conference & 
Expo, themed Stronger in Solidarity. Call for proposals and reviewers now 
open <http://conference.aashe.org/call-for-proposals>.

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by baronvonvaderham** [comment]
Neither did I, then I was working on that project for my algorithms class and I set my array length limit to like 10 million. Somewhere around 100,000 the code broke and said I'd exceeded the maximum recursion depth allowed for the interpreter.

**Comment by rerb** [comment]
That’s what I thought would happen.  Misunderstood what you were saying earlier.

On Feb 10, 2017, 12:32 PM -0500, Scott Johnson <notifications@github.com>, wrote:
> Neither did I, then I was working on that project for my algorithms class and I set my array length limit to like 10 million. Somewhere around 100,000 the code broke and said I'd exceeded the maximum recursion depth allowed for the interpreter.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

-- 
Join us in San Antonio, TX from Oct. 15 - 18 for the 2017 AASHE Conference & 
Expo, themed Stronger in Solidarity. Call for proposals and reviewers now 
open <http://conference.aashe.org/call-for-proposals>.

Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>
